/**
 * Generates docs/mcp-tools.generated.md from the live MCP tool registry.
 *
 * The tool arrays in apps/api/src/mcp/*.ts are the source of truth; this script
 * renders them to markdown so the docs can never drift from the code. CI runs it
 * and fails if the committed file is stale (see .github/workflows/ci.yml).
 *
 *   pnpm --filter @projektor/api gen:catalog
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { TOOL_COUNT, TOOL_DOMAINS } from "../src/mcp/catalog";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", ".."); // apps/api/scripts -> repo root
const outPath = join(repoRoot, "docs", "mcp-tools.generated.md");

function escapeCell(text: string): string {
	return text.replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();
}

const groups = ["Coordination", "Project data"] as const;
const domainCount = TOOL_DOMAINS.length;

const lines: string[] = [];
lines.push("<!-- GENERATED by apps/api/scripts/gen-mcp-catalog.ts — DO NOT EDIT BY HAND. -->");
lines.push("<!-- Run `pnpm --filter @projektor/api gen:catalog` after changing any mcp/*.ts tool. -->");
lines.push("");
lines.push("# MCP tool catalog");
lines.push("");
lines.push(
	`**${TOOL_COUNT} tools across ${domainCount} domains.** All inputs/outputs are JSON. ` +
		"Generated from `apps/api/src/mcp/*.ts` and freshness-checked by CI, so it always matches the running server.",
);
lines.push("");

for (const group of groups) {
	const domains = TOOL_DOMAINS.filter((d) => d.group === group);
	if (domains.length === 0) continue;
	lines.push(`## ${group}`);
	lines.push("");
	for (const d of domains) {
		lines.push(`### ${d.title}`);
		lines.push("");
		lines.push("| Tool | Description |");
		lines.push("|------|-------------|");
		for (const t of d.tools) {
			lines.push(`| \`${escapeCell(t.name)}\` | ${escapeCell(t.description)} |`);
		}
		lines.push("");
	}
}

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, `${lines.join("\n").trimEnd()}\n`, "utf8");
console.log(`Wrote ${outPath} (${TOOL_COUNT} tools, ${domainCount} domains)`);
