import type { MCPTool } from "@projektor/types";
import { agentMessagesTools } from "./agent-messages";
import { agentsTools } from "./agents";
import { commentsTools } from "./comments";
import { customFieldsTools } from "./custom-fields";
import { fileClaimsTools } from "./file-claims";
import { issueLinksTools } from "./issue-links";
import { issuesTools } from "./issues";
import { projectActivityTools } from "./project-activity";
import { projectsTools } from "./projects";
import { sprintsTools } from "./sprints";
import { taskStatusesTools } from "./task-statuses";
import { taskTypesTools } from "./task-types";
import { wikiTools } from "./wiki";
import { workspacesTools } from "./workspaces";

/**
 * A documentation-facing grouping of the MCP tool registry.
 *
 * This is the single source of truth for the tool catalog rendered in the docs
 * (docs/mcp-tools.generated.md, generated by scripts/gen-mcp-catalog.ts) — never
 * hand-maintain a tool table elsewhere. The runtime registry lives in
 * routes/mcp.ts; keep the two in the same order so the docs match dispatch.
 */
export interface ToolDomain {
	/** Stable slug, e.g. "issues". */
	domain: string;
	/** Human-facing heading. */
	title: string;
	/** Coordination = agent-native primitives; Data = project content/config. */
	group: "Coordination" | "Project data";
	tools: MCPTool[];
}

export const TOOL_DOMAINS: ToolDomain[] = [
	{ domain: "workspaces", title: "Workspaces & members", group: "Project data", tools: workspacesTools },
	{ domain: "projects", title: "Projects", group: "Project data", tools: projectsTools },
	{ domain: "project-activity", title: "Project activity", group: "Project data", tools: projectActivityTools },
	{ domain: "issues", title: "Issues", group: "Project data", tools: issuesTools },
	{ domain: "issue-links", title: "Issue links", group: "Project data", tools: issueLinksTools },
	{ domain: "comments", title: "Comments", group: "Project data", tools: commentsTools },
	{ domain: "wiki", title: "Wiki", group: "Project data", tools: wikiTools },
	{ domain: "task-types", title: "Task types", group: "Project data", tools: taskTypesTools },
	{ domain: "task-statuses", title: "Task statuses", group: "Project data", tools: taskStatusesTools },
	{ domain: "custom-fields", title: "Custom fields", group: "Project data", tools: customFieldsTools },
	{ domain: "sprints", title: "Sprints", group: "Project data", tools: sprintsTools },
	{ domain: "agents", title: "Agent sessions", group: "Coordination", tools: agentsTools },
	{ domain: "file-claims", title: "File claims", group: "Coordination", tools: fileClaimsTools },
	{ domain: "agent-messages", title: "Agent messages", group: "Coordination", tools: agentMessagesTools },
];

/** Total number of MCP tools across all domains. */
export const TOOL_COUNT = TOOL_DOMAINS.reduce((n, d) => n + d.tools.length, 0);
